# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets :
        miniature : 
            quality : 85
            filters : 
                thumbnail:
                    size: [820, 480]
                    mode : outbound
        welcome : 
            quality : 100
            filters : 
                scale : 
                    dim : [1600, 1600]
        professionnel :
            quality : 75
            filters :
                scale : 
                    dim : [800, 800]
        photo : 
            quality : 75
            filters : 
                scale : 
                    dim : [600, 600]


